"""empty message

Revision ID: 353ccd3d30a4
Revises: 7f8c5887a1b9
Create Date: 2026-06-27 13:05:31.789105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '353ccd3d30a4'
down_revision: Union[str, Sequence[str], None] = '7f8c5887a1b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userprofile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("'Gdańsk'"), nullable=False))
        batch_op.add_column(sa.Column('district', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("('')"), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userprofile', schema=None) as batch_op:
        batch_op.drop_column('district')
        batch_op.drop_column('city')

    # ### end Alembic commands ###
